version: '2'
services:
  atom_php:
    build: .
    command: bash -c "sh ./integration_test/run_integration.sh"
    environment:
      USING_S3: "no" # yes - false
      STREAM: "sdkdev_sdkdev.public.g8y3etest"
      AUTH: "I40iwPPOsG3dfWX30labriCg9HqMfL"
      BULK_SIZE: 64
      BULK_SIZE_BYTE: 65536
      FLUSH_INTERVAL: 10000 # milliseconds
      DATA_TYPES: '{"id": "int", "string": "str"}' # types: int, str, bool
      DATA_INCREMENT_KEY: "id" 
      EVENT_COUNT: 1000